<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\key\brightstardb.snk</AssemblyOriginatorKeyFile>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefineConstants>$(DefineConstants);NETSTANDARD20</DefineConstants>
    <PackageId>BrightstarDBLibs</PackageId>
    <Title>BrightstarDB Core Library</Title>
    <Description>BrightstarDB is a fast and scalable NoSQL database for .NET with code-first data model generation. This package installs the BrightstarDB libraries alone without any code-generation support.</Description>
    <Authors>kal_ahmed</Authors>
    <PackageProjectUrl>http://brightstardb.com/</PackageProjectUrl>
    <PackageIconUrl>http://brightstardb.com/images/logo-nuget.png</PackageIconUrl>
    <Copyright>Copyright 2019 Khalil Ahmed, Graham Moore, and other contributor</Copyright>
    <PackageTags>brightstardb;rdf;nosql;database;sparql</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <AssemblyName>BrightstarDB</AssemblyName>
    <RootNamespace>BrightstarDB</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="dotNetRdf" />
    <PackageReference Include="Remotion.Linq" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="obj\**\*.cs;OData\*.cs" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

</Project>