<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\BrightstarDB\BrightstarDB.csproj" />
    <ProjectReference Include="..\BrightstarDB.CodeGeneration\BrightstarDB.CodeGeneration.csproj" />
    <EmbeddedResource Include="GeneratorTestsResources\*.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Update="EntityContext.tt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
 
</Project>